/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-11-11 11:07:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"signUp.css\">\r\n");
      out.write("<title>Sign Up</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"outest_container\" id=\"outest\">\r\n");
      out.write("\t\t\t<div class=\"form_ele\">User Name:<input type=\"text\" name=\"uname\"></div>\r\n");
      out.write("\t\t\t<div class=\"form_ele\">Re-enter name:<input type=\"text\" name=\"uname_re\"></div>\r\n");
      out.write("\t\t\t<div class=\"form_ele\">User Password:<input type=\"password\" name=\"upass\"></div>\r\n");
      out.write("\t\t\t<div class=\"form_ele\">Re-enter password:<input type=\"password\" name=\"upass_re\">\r\n");
      out.write("\t\t\t\t<img onclick=\"submit()\" src=\"10.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form_ele\" id=\"hidden_status\">Hidden Part</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" >\r\n");
      out.write("\r\n");
      out.write("\t\tfunction submit(){\r\n");
      out.write("\t\t\tconsole.log(\"Submitting\");\r\n");
      out.write("\t\t\tuid = document.getElementsByName(\"uname\")[0].value;\r\n");
      out.write("\t\t\tupass = document.getElementsByName(\"upass\")[0].value;\r\n");
      out.write("\r\n");
      out.write("\t\t\tuid_re = document.getElementsByName(\"uname_re\")[0].value;\r\n");
      out.write("\t\t\tupass_re = document.getElementsByName(\"upass_re\")[0].value;\r\n");
      out.write("\t\t\tif(uid == uid_re && upass == upass_re && uid !==\"\" && upass !== \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar xhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\txhr.open(\"GET\",\"signUp.do?uid=\"+uid+\"&upass=\"+upass);\r\n");
      out.write("\t\t\t\txhr.onreadystatechange = function()\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t            \tif(xhr.readyState==4 && xhr.status == 200)\r\n");
      out.write("\t            \t{\r\n");
      out.write("\t\t                console.info(xhr.responseText);\r\n");
      out.write("\t\t                var responseString = xhr.responseText;\r\n");
      out.write("\t\t                var status = document.getElementById(\"hidden_status\");\r\n");
      out.write("\t\t                status.style.visibility = \"visible\";\r\n");
      out.write("\t\t                status.innerHTML= responseString;\r\n");
      out.write("\t\t            }\r\n");
      out.write("   \t\t \t\t}\r\n");
      out.write("    \t\t\txhr.send(null);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tvar status = document.getElementById(\"hidden_status\");\r\n");
      out.write("\t\t        status.style.visibility = \"visible\";\r\n");
      out.write("\t\t        status.innerHTML= \"Please make sure your two passwords and usernames are same\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
